/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.antsstyle.artretweeter.gui;

/**
 *
 * @author antss
 */
public class PrimaryDisplayPanel extends javax.swing.JPanel {

    /**
     * Creates new form PrimaryDisplayPanel
     */
    public PrimaryDisplayPanel() {
        initComponents();
    }

    /**
     * Gets the panel currently being displayed inside this one.
     *
     * @return The panel being displayed inside this panel.
     */
    protected javax.swing.JPanel getDisplayAreaPanel() {
        return displayAreaPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        displayAreaPanel = new javax.swing.JPanel();
        mainMenuToolBar = new javax.swing.JToolBar();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        goToAccountsButton = new com.antsstyle.artretweeter.gui.WWButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        goToTweetsButton = new com.antsstyle.artretweeter.gui.WWButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        goToRetweetQueuingButton = new com.antsstyle.artretweeter.gui.WWButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();

        displayAreaPanel.setMaximumSize(new java.awt.Dimension(1820, 1080));

        javax.swing.GroupLayout displayAreaPanelLayout = new javax.swing.GroupLayout(displayAreaPanel);
        displayAreaPanel.setLayout(displayAreaPanelLayout);
        displayAreaPanelLayout.setHorizontalGroup(
            displayAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 771, Short.MAX_VALUE)
        );
        displayAreaPanelLayout.setVerticalGroup(
            displayAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 535, Short.MAX_VALUE)
        );

        mainMenuToolBar.setFloatable(false);
        mainMenuToolBar.setOrientation(javax.swing.SwingConstants.VERTICAL);
        mainMenuToolBar.setRollover(true);
        mainMenuToolBar.add(jSeparator3);

        goToAccountsButton.setText("Accounts");
        goToAccountsButton.setFocusable(false);
        goToAccountsButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        goToAccountsButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        goToAccountsButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        goToAccountsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goToAccountsButtonActionPerformed(evt);
            }
        });
        mainMenuToolBar.add(goToAccountsButton);
        mainMenuToolBar.add(jSeparator1);

        goToTweetsButton.setText("Tweet Management");
        goToTweetsButton.setFocusable(false);
        goToTweetsButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        goToTweetsButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        goToTweetsButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        goToTweetsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goToTweetsButtonActionPerformed(evt);
            }
        });
        mainMenuToolBar.add(goToTweetsButton);
        mainMenuToolBar.add(jSeparator2);

        goToRetweetQueuingButton.setText("Retweet Queuing");
        goToRetweetQueuingButton.setToolTipText("");
        goToRetweetQueuingButton.setFocusable(false);
        goToRetweetQueuingButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        goToRetweetQueuingButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        goToRetweetQueuingButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        goToRetweetQueuingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goToRetweetQueuingButtonActionPerformed(evt);
            }
        });
        mainMenuToolBar.add(goToRetweetQueuingButton);
        mainMenuToolBar.add(jSeparator4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(mainMenuToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(displayAreaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(displayAreaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mainMenuToolBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void goToAccountsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goToAccountsButtonActionPerformed
        GUI.getInstance().switchPanels(GUI.getAccountsPanel());
    }//GEN-LAST:event_goToAccountsButtonActionPerformed

    private void goToTweetsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goToTweetsButtonActionPerformed
       GUI.getInstance().switchPanels(GUI.getTweetsPanel());
    }//GEN-LAST:event_goToTweetsButtonActionPerformed

    private void goToRetweetQueuingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goToRetweetQueuingButtonActionPerformed
        GUI.getInstance().switchPanels(GUI.getQueuingPanel());
    }//GEN-LAST:event_goToRetweetQueuingButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel displayAreaPanel;
    private com.antsstyle.artretweeter.gui.WWButton goToAccountsButton;
    private com.antsstyle.artretweeter.gui.WWButton goToRetweetQueuingButton;
    private com.antsstyle.artretweeter.gui.WWButton goToTweetsButton;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    protected javax.swing.JToolBar mainMenuToolBar;
    // End of variables declaration//GEN-END:variables
}
