/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.antsstyle.artretweeter.gui;

/**
 *
 * @author antss
 */
public class PrimaryDisplayPanel extends javax.swing.JPanel {

    /**
     * Creates new form PrimaryDisplayPanel
     */
    public PrimaryDisplayPanel() {
        initComponents();
    }

    public void setFailedRetweetsButtonText(int numNotifications) {
        if (numNotifications == 0) {
            goToFailedRetweetsButton.setText("Failed Retweets");
        } else if (numNotifications > 0 && numNotifications < 100) {
            String text = "Failed Retweets (".concat(String.valueOf(numNotifications)).concat(")");
            goToFailedRetweetsButton.setText(text);
        } else if (numNotifications >= 100) {
            goToFailedRetweetsButton.setText("Failed Retweets (99+)");
        }
    }

    /**
     * Gets the panel currently being displayed inside this one.
     *
     * @return The panel being displayed inside this panel.
     */
    protected javax.swing.JPanel getDisplayAreaPanel() {
        return displayAreaPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        displayAreaPanel = new javax.swing.JPanel();
        mainMenuToolBar = new javax.swing.JToolBar();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        goToAccountsButton = new com.antsstyle.artretweeter.gui.WWButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        goToPrimaryPanelButton = new com.antsstyle.artretweeter.gui.WWButton();
        jSeparator10 = new javax.swing.JToolBar.Separator();
        goToFailedRetweetsButton = new com.antsstyle.artretweeter.gui.WWButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        goToConfigurationPanel = new com.antsstyle.artretweeter.gui.WWButton();
        jSeparator8 = new javax.swing.JToolBar.Separator();
        goToHelpAndInfoButton = new com.antsstyle.artretweeter.gui.WWButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();

        displayAreaPanel.setMaximumSize(new java.awt.Dimension(1820, 1080));

        javax.swing.GroupLayout displayAreaPanelLayout = new javax.swing.GroupLayout(displayAreaPanel);
        displayAreaPanel.setLayout(displayAreaPanelLayout);
        displayAreaPanelLayout.setHorizontalGroup(
            displayAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 788, Short.MAX_VALUE)
        );
        displayAreaPanelLayout.setVerticalGroup(
            displayAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 535, Short.MAX_VALUE)
        );

        mainMenuToolBar.setFloatable(false);
        mainMenuToolBar.setOrientation(javax.swing.SwingConstants.VERTICAL);
        mainMenuToolBar.setRollover(true);
        mainMenuToolBar.add(jSeparator3);

        goToAccountsButton.setText("Accounts");
        goToAccountsButton.setFocusable(false);
        goToAccountsButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        goToAccountsButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        goToAccountsButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        goToAccountsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goToAccountsButtonActionPerformed(evt);
            }
        });
        mainMenuToolBar.add(goToAccountsButton);
        mainMenuToolBar.add(jSeparator1);

        goToPrimaryPanelButton.setText("Tweet Management");
        goToPrimaryPanelButton.setToolTipText("");
        goToPrimaryPanelButton.setFocusable(false);
        goToPrimaryPanelButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        goToPrimaryPanelButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        goToPrimaryPanelButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        goToPrimaryPanelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goToPrimaryPanelButtonActionPerformed(evt);
            }
        });
        mainMenuToolBar.add(goToPrimaryPanelButton);
        mainMenuToolBar.add(jSeparator10);

        goToFailedRetweetsButton.setText("Failed Retweets");
        goToFailedRetweetsButton.setToolTipText("");
        goToFailedRetweetsButton.setFocusable(false);
        goToFailedRetweetsButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        goToFailedRetweetsButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        goToFailedRetweetsButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        goToFailedRetweetsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goToFailedRetweetsButtonActionPerformed(evt);
            }
        });
        mainMenuToolBar.add(goToFailedRetweetsButton);
        mainMenuToolBar.add(jSeparator5);

        goToConfigurationPanel.setText("Configuration");
        goToConfigurationPanel.setToolTipText("");
        goToConfigurationPanel.setFocusable(false);
        goToConfigurationPanel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        goToConfigurationPanel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        goToConfigurationPanel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        goToConfigurationPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goToConfigurationPanelActionPerformed(evt);
            }
        });
        mainMenuToolBar.add(goToConfigurationPanel);
        mainMenuToolBar.add(jSeparator8);

        goToHelpAndInfoButton.setText("Help & Info");
        goToHelpAndInfoButton.setToolTipText("");
        goToHelpAndInfoButton.setFocusable(false);
        goToHelpAndInfoButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        goToHelpAndInfoButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        goToHelpAndInfoButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        goToHelpAndInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goToHelpAndInfoButtonActionPerformed(evt);
            }
        });
        mainMenuToolBar.add(goToHelpAndInfoButton);
        mainMenuToolBar.add(jSeparator6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(mainMenuToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(displayAreaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(displayAreaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mainMenuToolBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void goToAccountsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goToAccountsButtonActionPerformed
        GUI.getInstance().switchPanels(GUI.getAccountsPanel());
    }//GEN-LAST:event_goToAccountsButtonActionPerformed

    private void goToFailedRetweetsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goToFailedRetweetsButtonActionPerformed
        GUI.getInstance().switchPanels(GUI.getFailedRetweetsPanel());
    }//GEN-LAST:event_goToFailedRetweetsButtonActionPerformed

    private void goToHelpAndInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goToHelpAndInfoButtonActionPerformed
        GUI.getInstance().switchPanels(GUI.getHelpPanel());
    }//GEN-LAST:event_goToHelpAndInfoButtonActionPerformed

    private void goToConfigurationPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goToConfigurationPanelActionPerformed
        GUI.getInstance().switchPanels(GUI.getConfigurationPanel());
    }//GEN-LAST:event_goToConfigurationPanelActionPerformed

    private void goToPrimaryPanelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goToPrimaryPanelButtonActionPerformed
        GUI.getInstance().switchPanels(GUI.getPrimaryPanel());
    }//GEN-LAST:event_goToPrimaryPanelButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel displayAreaPanel;
    private com.antsstyle.artretweeter.gui.WWButton goToAccountsButton;
    private com.antsstyle.artretweeter.gui.WWButton goToConfigurationPanel;
    private com.antsstyle.artretweeter.gui.WWButton goToFailedRetweetsButton;
    private com.antsstyle.artretweeter.gui.WWButton goToHelpAndInfoButton;
    private com.antsstyle.artretweeter.gui.WWButton goToPrimaryPanelButton;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator10;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator8;
    protected javax.swing.JToolBar mainMenuToolBar;
    // End of variables declaration//GEN-END:variables
}
