/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.antsstyle.artretweeter.gui;

import com.antsstyle.artretweeter.datastructures.CachedVariable;
import com.antsstyle.artretweeter.datastructures.TableFilterEntry;
import com.antsstyle.artretweeter.db.CachedVariableDB;
import java.util.ArrayList;
import org.apache.commons.lang3.StringUtils;

/**
 *
 * @author antss
 */
public class SetTableFilteringPanel extends javax.swing.JPanel {

    /**
     * Creates new form SetTableFilteringPanel
     */
    public SetTableFilteringPanel() {
        initComponents();
    }

    public ArrayList<TableFilterEntry> getUserSettings() {
        ArrayList<TableFilterEntry> settings = new ArrayList<>();
        settings.add(new TableFilterEntry("id", idFilterCheckBox.isSelected(), (String) idFilterOperatorComboBox.getSelectedItem(),
                idFilterField.getText()));
        settings.add(new TableFilterEntry("created_at", datePostedFilterCheckBox.isSelected(),
                (String) datePostedFilterOperatorComboBox.getSelectedItem(), datePostedFilterField.getText()));
        settings.add(new TableFilterEntry("numretweets", rtNumberFilterCheckBox.isSelected(),
                (String) rtNumberFilterOperatorComboBox.getSelectedItem(), rtNumberFilterField.getText()));
        settings.add(new TableFilterEntry("pendingrt", pendingRTFilterCheckBox.isSelected(),
                (String) pendingRTFilterOperatorComboBox.getSelectedItem(), pendingRTFilterFieldCheckBox.isSelected() ? "true" : "false"));
        return settings;
    }

    public void setComboBoxSettings() {
        CachedVariable managementTweetTableSorting = CachedVariableDB.getCachedVariableByName("artretweeter.managementtweettablefiltering");
        if (managementTweetTableSorting != null) {
            String[] items = StringUtils.split(managementTweetTableSorting.getValue(), ";");
            idFilterCheckBox.setSelected(items[1].equals("true"));
            idFilterOperatorComboBox.setSelectedItem(items[2]);
            if (items[3].equals("null")) {
                idFilterField.setText("");
            } else {
                idFilterField.setText(items[3]);
            }
            datePostedFilterCheckBox.setSelected(items[5].equals("true"));
            datePostedFilterOperatorComboBox.setSelectedItem(items[6]);
            if (items[7].equals("null")) {
                datePostedFilterField.setText("");
            } else {
                datePostedFilterField.setText(items[7]);
            }
            rtNumberFilterCheckBox.setSelected(items[9].equals("true"));
            rtNumberFilterOperatorComboBox.setSelectedItem(items[10]);
            if (items[11].equals("null")) {
                rtNumberFilterField.setText("");
            } else {
                rtNumberFilterField.setText(items[11]);
            }
            pendingRTFilterCheckBox.setSelected(items[13].equals("true"));
            pendingRTFilterOperatorComboBox.setSelectedItem(items[14]);
            if (items[15].equals("null") || items[15].equals("false")) {
                pendingRTFilterFieldCheckBox.setSelected(false);
            } else {
                pendingRTFilterFieldCheckBox.setSelected(items[15].equals("true"));
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        idFilterOperatorComboBox = new javax.swing.JComboBox<>();
        rtNumberFilterOperatorComboBox = new javax.swing.JComboBox<>();
        datePostedFilterOperatorComboBox = new javax.swing.JComboBox<>();
        idFilterCheckBox = new javax.swing.JCheckBox();
        datePostedFilterCheckBox = new javax.swing.JCheckBox();
        rtNumberFilterCheckBox = new javax.swing.JCheckBox();
        idFilterField = new javax.swing.JTextField();
        datePostedFilterField = new javax.swing.JTextField();
        rtNumberFilterField = new javax.swing.JTextField();
        pendingRTFilterCheckBox = new javax.swing.JCheckBox();
        pendingRTFilterOperatorComboBox = new javax.swing.JComboBox<>();
        pendingRTFilterFieldCheckBox = new javax.swing.JCheckBox();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Show only tweets with the following:");

        idFilterOperatorComboBox.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        idFilterOperatorComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { ">", "<", "=" }));
        idFilterOperatorComboBox.setLightWeightPopupEnabled(false);
        idFilterOperatorComboBox.setMaximumSize(new java.awt.Dimension(51, 25));
        idFilterOperatorComboBox.setMinimumSize(new java.awt.Dimension(51, 25));
        idFilterOperatorComboBox.setPreferredSize(new java.awt.Dimension(51, 25));

        rtNumberFilterOperatorComboBox.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rtNumberFilterOperatorComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { ">", "<", "=" }));
        rtNumberFilterOperatorComboBox.setLightWeightPopupEnabled(false);
        rtNumberFilterOperatorComboBox.setMaximumSize(new java.awt.Dimension(51, 25));
        rtNumberFilterOperatorComboBox.setMinimumSize(new java.awt.Dimension(51, 25));
        rtNumberFilterOperatorComboBox.setPreferredSize(new java.awt.Dimension(51, 25));

        datePostedFilterOperatorComboBox.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        datePostedFilterOperatorComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { ">", "<", "=" }));
        datePostedFilterOperatorComboBox.setLightWeightPopupEnabled(false);
        datePostedFilterOperatorComboBox.setMaximumSize(new java.awt.Dimension(51, 25));
        datePostedFilterOperatorComboBox.setMinimumSize(new java.awt.Dimension(51, 25));
        datePostedFilterOperatorComboBox.setPreferredSize(new java.awt.Dimension(51, 25));

        idFilterCheckBox.setText("ID");
        idFilterCheckBox.setMaximumSize(new java.awt.Dimension(125, 24));
        idFilterCheckBox.setMinimumSize(new java.awt.Dimension(125, 24));
        idFilterCheckBox.setPreferredSize(new java.awt.Dimension(125, 24));

        datePostedFilterCheckBox.setText("Date Posted");
        datePostedFilterCheckBox.setMaximumSize(new java.awt.Dimension(125, 24));
        datePostedFilterCheckBox.setMinimumSize(new java.awt.Dimension(125, 24));
        datePostedFilterCheckBox.setPreferredSize(new java.awt.Dimension(125, 24));

        rtNumberFilterCheckBox.setText("RT#");
        rtNumberFilterCheckBox.setMaximumSize(new java.awt.Dimension(125, 24));
        rtNumberFilterCheckBox.setMinimumSize(new java.awt.Dimension(125, 24));
        rtNumberFilterCheckBox.setPreferredSize(new java.awt.Dimension(125, 24));

        pendingRTFilterCheckBox.setText("Pending RT");
        pendingRTFilterCheckBox.setMaximumSize(new java.awt.Dimension(125, 24));
        pendingRTFilterCheckBox.setMinimumSize(new java.awt.Dimension(125, 24));
        pendingRTFilterCheckBox.setPreferredSize(new java.awt.Dimension(125, 24));

        pendingRTFilterOperatorComboBox.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pendingRTFilterOperatorComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "=" }));
        pendingRTFilterOperatorComboBox.setLightWeightPopupEnabled(false);
        pendingRTFilterOperatorComboBox.setMaximumSize(new java.awt.Dimension(51, 25));
        pendingRTFilterOperatorComboBox.setMinimumSize(new java.awt.Dimension(51, 25));
        pendingRTFilterOperatorComboBox.setPreferredSize(new java.awt.Dimension(51, 25));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(pendingRTFilterCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pendingRTFilterOperatorComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pendingRTFilterFieldCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(rtNumberFilterCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(datePostedFilterCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idFilterCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(idFilterOperatorComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(datePostedFilterOperatorComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(rtNumberFilterOperatorComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(idFilterField)
                            .addComponent(datePostedFilterField)
                            .addComponent(rtNumberFilterField, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idFilterOperatorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idFilterCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(datePostedFilterOperatorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(datePostedFilterCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(datePostedFilterField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rtNumberFilterOperatorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rtNumberFilterCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rtNumberFilterField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(idFilterField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pendingRTFilterOperatorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pendingRTFilterCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pendingRTFilterFieldCheckBox))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox datePostedFilterCheckBox;
    private javax.swing.JTextField datePostedFilterField;
    private javax.swing.JComboBox<String> datePostedFilterOperatorComboBox;
    private javax.swing.JCheckBox idFilterCheckBox;
    private javax.swing.JTextField idFilterField;
    private javax.swing.JComboBox<String> idFilterOperatorComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox pendingRTFilterCheckBox;
    private javax.swing.JCheckBox pendingRTFilterFieldCheckBox;
    private javax.swing.JComboBox<String> pendingRTFilterOperatorComboBox;
    private javax.swing.JCheckBox rtNumberFilterCheckBox;
    private javax.swing.JTextField rtNumberFilterField;
    private javax.swing.JComboBox<String> rtNumberFilterOperatorComboBox;
    // End of variables declaration//GEN-END:variables
}
