/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.antsstyle.artretweeter.gui.tweetpanels;

import com.antsstyle.artretweeter.datastructures.Account;
import com.antsstyle.artretweeter.datastructures.AutomationSettingsHolder;
import com.antsstyle.artretweeter.gui.GUI;
import com.antsstyle.artretweeter.gui.GUIHelperMethods;

/**
 *
 * @author antss
 */
public class AutomationMetricsDisabledSubPanel extends javax.swing.JPanel {

    /**
     * Creates new form AutomationMetricsDisabledSubPanel
     */
    public AutomationMetricsDisabledSubPanel() {
        initComponents();
    }

    public void initialise(AutomationSettingsHolder holder) {
        setMetricsDisabledText(holder);
    }

    public void setMetricsDisabledText(AutomationSettingsHolder holder) {
        if (holder != null) {
            metricsDisabledTextLabel.setText(" Metrics options are hidden (your current metrics settings are in effect). "
                    + "Click the button on the right to view them.");
        } else {
            metricsDisabledTextLabel.setText(" Metrics options are hidden (ArtRetweeter will set them automatically). "
                    + "Click the button on the right to view them.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        metricsDisabledTextLabel = new javax.swing.JLabel();
        showMetricsOptionsButton = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(1046, 38));
        setMinimumSize(new java.awt.Dimension(1046, 38));

        metricsDisabledTextLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        metricsDisabledTextLabel.setText(" Metrics options are currently hidden (ArtRetweeter will decide automatically). Click the button on the right to show them.");
        metricsDisabledTextLabel.setMaximumSize(new java.awt.Dimension(450, 32));
        metricsDisabledTextLabel.setMinimumSize(new java.awt.Dimension(450, 32));
        metricsDisabledTextLabel.setPreferredSize(new java.awt.Dimension(450, 32));

        showMetricsOptionsButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        showMetricsOptionsButton.setText("Show metrics options");
        showMetricsOptionsButton.setMaximumSize(new java.awt.Dimension(175, 32));
        showMetricsOptionsButton.setMinimumSize(new java.awt.Dimension(175, 32));
        showMetricsOptionsButton.setPreferredSize(new java.awt.Dimension(175, 32));
        showMetricsOptionsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showMetricsOptionsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(metricsDisabledTextLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 859, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(showMetricsOptionsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(metricsDisabledTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showMetricsOptionsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void showMetricsOptionsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showMetricsOptionsButtonActionPerformed
        showMetricsOptionsButton.setEnabled(false);
        forceShowMetricsOptions();
        showMetricsOptionsButton.setEnabled(true);
    }//GEN-LAST:event_showMetricsOptionsButtonActionPerformed

    private void forceShowMetricsOptions() {
        GUI.getAutomationPanel().setMetricsOptionsPanel(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel metricsDisabledTextLabel;
    private javax.swing.JButton showMetricsOptionsButton;
    // End of variables declaration//GEN-END:variables
}
