/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.antsstyle.artretweeter.gui.configuration;

import com.antsstyle.artretweeter.configuration.Config;
import com.antsstyle.artretweeter.configuration.ConfigurationModule;
import com.antsstyle.artretweeter.configuration.GUIConfig;
import com.antsstyle.artretweeter.db.ConfigDB;
import com.antsstyle.artretweeter.db.CoreDB;
import com.antsstyle.artretweeter.db.DBResponse;
import com.antsstyle.artretweeter.db.DBTable;
import com.antsstyle.artretweeter.gui.GUI;
import com.antsstyle.artretweeter.gui.GUIHelperMethods;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JColorChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.plaf.ColorUIResource;

/**
 *
 * @author antss
 */
public class AppearanceConfigurationPanel extends ConfigurationSubPanel {

    /**
     * Creates new form AppearanceConfigurationPanel
     */
    public AppearanceConfigurationPanel() {
        super(Config.guiConfig);
        initComponents();
        windowBackgroundColourLabel.setBackground(GUIConfig.WINDOW_BG_COLOUR);
        windowFontColourLabel.setBackground(GUIConfig.WINDOW_FONT_COLOUR);
        buttonBackgroundColourLabel.setBackground(GUIConfig.JBUTTON_BG_COLOUR);
        buttonFontColourLabel.setBackground(GUIConfig.JBUTTON_FONT_COLOUR);
        GUIHelperMethods.setOppositeColourDashedBorder(windowFontColourLabel);
        GUIHelperMethods.setOppositeColourDashedBorder(buttonBackgroundColourLabel);
        GUIHelperMethods.setOppositeColourDashedBorder(buttonFontColourLabel);
        GUIHelperMethods.setOppositeColourDashedBorder(windowBackgroundColourLabel);
    }
    
    

    @Override
    public void commitChanges() {
        ArrayList<String> namesToUpdate = new ArrayList<>();
        ArrayList<Color> valuesToUpdate = new ArrayList<>();
        namesToUpdate.add(GUIConfig.P_JBUTTON_BG_COLOUR);
        namesToUpdate.add(GUIConfig.P_JBUTTON_FONT_COLOUR);
        namesToUpdate.add(GUIConfig.P_WINDOW_BG_COLOUR);
        namesToUpdate.add(GUIConfig.P_WINDOW_FONT_COLOUR);
        valuesToUpdate.add(GUIConfig.JBUTTON_BG_COLOUR);
        valuesToUpdate.add(GUIConfig.JBUTTON_FONT_COLOUR);
        valuesToUpdate.add(GUIConfig.WINDOW_BG_COLOUR);
        valuesToUpdate.add(GUIConfig.WINDOW_FONT_COLOUR);
        ArrayList<Object[]> params = new ArrayList<>();
        for (int i = 0; i < namesToUpdate.size(); i++) {
            params.add(new Object[]{namesToUpdate.get(i),
                ConfigurationModule.convertConfigItemToString(valuesToUpdate.get(i))});
        }

        boolean success = ConfigDB.updateConfigItems(params);
        if (!success) {
            String message = "Failed to commit appearance changes.";
            JOptionPane.showMessageDialog(GUI.getInstance(), message, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel17 = new javax.swing.JLabel();
        jPanel36 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        windowBackgroundColourChooserButton = new javax.swing.JButton();
        buttonBackgroundColourChooserButton = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        windowBackgroundColourLabel = new com.antsstyle.artretweeter.gui.configuration.ColourPreviewLabel();
        buttonBackgroundColourLabel = new com.antsstyle.artretweeter.gui.configuration.ColourPreviewLabel();
        buttonBackgroundColourRevertButton = new javax.swing.JButton();
        windowBackgroundColourRevertButton = new javax.swing.JButton();
        jPanel37 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        buttonFontColourChooserButton = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        labelFontColourChooserButton = new javax.swing.JButton();
        windowFontColourLabel = new com.antsstyle.artretweeter.gui.configuration.ColourPreviewLabel();
        buttonFontColourLabel = new com.antsstyle.artretweeter.gui.configuration.ColourPreviewLabel();
        windowFontColourRevertButton = new javax.swing.JButton();
        buttonFontColourRevertButton = new javax.swing.JButton();

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Colours");

        jLabel19.setText("Button background colour:");
        jLabel19.setMaximumSize(new java.awt.Dimension(174, 26));
        jLabel19.setMinimumSize(new java.awt.Dimension(174, 26));
        jLabel19.setPreferredSize(new java.awt.Dimension(174, 26));

        windowBackgroundColourChooserButton.setText("Select");
        windowBackgroundColourChooserButton.setMaximumSize(new java.awt.Dimension(70, 26));
        windowBackgroundColourChooserButton.setMinimumSize(new java.awt.Dimension(70, 26));
        windowBackgroundColourChooserButton.setPreferredSize(new java.awt.Dimension(70, 26));
        windowBackgroundColourChooserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                windowBackgroundColourChooserButtonActionPerformed(evt);
            }
        });

        buttonBackgroundColourChooserButton.setText("Select");
        buttonBackgroundColourChooserButton.setMaximumSize(new java.awt.Dimension(70, 26));
        buttonBackgroundColourChooserButton.setMinimumSize(new java.awt.Dimension(70, 26));
        buttonBackgroundColourChooserButton.setPreferredSize(new java.awt.Dimension(70, 26));
        buttonBackgroundColourChooserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBackgroundColourChooserButtonActionPerformed(evt);
            }
        });

        jLabel18.setText("Window background colour:");
        jLabel18.setMaximumSize(new java.awt.Dimension(174, 26));
        jLabel18.setMinimumSize(new java.awt.Dimension(174, 26));
        jLabel18.setPreferredSize(new java.awt.Dimension(174, 26));

        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Background Colours");

        windowBackgroundColourLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        windowBackgroundColourLabel.setMaximumSize(new java.awt.Dimension(26, 26));
        windowBackgroundColourLabel.setMinimumSize(new java.awt.Dimension(26, 26));
        windowBackgroundColourLabel.setOpaque(true);
        windowBackgroundColourLabel.setPreferredSize(new java.awt.Dimension(26, 26));

        buttonBackgroundColourLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        buttonBackgroundColourLabel.setMaximumSize(new java.awt.Dimension(26, 26));
        buttonBackgroundColourLabel.setMinimumSize(new java.awt.Dimension(26, 26));
        buttonBackgroundColourLabel.setOpaque(true);
        buttonBackgroundColourLabel.setPreferredSize(new java.awt.Dimension(26, 26));

        buttonBackgroundColourRevertButton.setText("Revert to default");
        buttonBackgroundColourRevertButton.setMaximumSize(new java.awt.Dimension(70, 26));
        buttonBackgroundColourRevertButton.setMinimumSize(new java.awt.Dimension(70, 26));
        buttonBackgroundColourRevertButton.setPreferredSize(new java.awt.Dimension(70, 26));
        buttonBackgroundColourRevertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBackgroundColourRevertButtonActionPerformed(evt);
            }
        });

        windowBackgroundColourRevertButton.setText("Revert to default");
        windowBackgroundColourRevertButton.setMaximumSize(new java.awt.Dimension(70, 26));
        windowBackgroundColourRevertButton.setMinimumSize(new java.awt.Dimension(70, 26));
        windowBackgroundColourRevertButton.setPreferredSize(new java.awt.Dimension(70, 26));
        windowBackgroundColourRevertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                windowBackgroundColourRevertButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel36Layout = new javax.swing.GroupLayout(jPanel36);
        jPanel36.setLayout(jPanel36Layout);
        jPanel36Layout.setHorizontalGroup(
            jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel36Layout.createSequentialGroup()
                .addGroup(jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(windowBackgroundColourLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonBackgroundColourLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel36Layout.createSequentialGroup()
                        .addComponent(windowBackgroundColourChooserButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(windowBackgroundColourRevertButton, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel36Layout.createSequentialGroup()
                        .addComponent(buttonBackgroundColourChooserButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonBackgroundColourRevertButton, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 131, Short.MAX_VALUE))
            .addGroup(jPanel36Layout.createSequentialGroup()
                .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel36Layout.setVerticalGroup(
            jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel36Layout.createSequentialGroup()
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(windowBackgroundColourChooserButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(windowBackgroundColourRevertButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(windowBackgroundColourLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buttonBackgroundColourChooserButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(buttonBackgroundColourRevertButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonBackgroundColourLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("Font Colours");

        jLabel20.setText("Button font colour:");
        jLabel20.setMaximumSize(new java.awt.Dimension(174, 26));
        jLabel20.setMinimumSize(new java.awt.Dimension(174, 26));
        jLabel20.setPreferredSize(new java.awt.Dimension(174, 26));

        buttonFontColourChooserButton.setText("Select");
        buttonFontColourChooserButton.setMaximumSize(new java.awt.Dimension(70, 26));
        buttonFontColourChooserButton.setMinimumSize(new java.awt.Dimension(70, 26));
        buttonFontColourChooserButton.setPreferredSize(new java.awt.Dimension(70, 26));
        buttonFontColourChooserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFontColourChooserButtonActionPerformed(evt);
            }
        });

        jLabel22.setText("Window font colour:");
        jLabel22.setMaximumSize(new java.awt.Dimension(174, 26));
        jLabel22.setMinimumSize(new java.awt.Dimension(174, 26));
        jLabel22.setPreferredSize(new java.awt.Dimension(174, 26));

        labelFontColourChooserButton.setText("Select");
        labelFontColourChooserButton.setMaximumSize(new java.awt.Dimension(70, 26));
        labelFontColourChooserButton.setMinimumSize(new java.awt.Dimension(70, 26));
        labelFontColourChooserButton.setPreferredSize(new java.awt.Dimension(70, 26));
        labelFontColourChooserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labelFontColourChooserButtonActionPerformed(evt);
            }
        });

        windowFontColourLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        windowFontColourLabel.setMaximumSize(new java.awt.Dimension(26, 26));
        windowFontColourLabel.setMinimumSize(new java.awt.Dimension(26, 26));
        windowFontColourLabel.setOpaque(true);
        windowFontColourLabel.setPreferredSize(new java.awt.Dimension(26, 26));

        buttonFontColourLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        buttonFontColourLabel.setMaximumSize(new java.awt.Dimension(26, 26));
        buttonFontColourLabel.setMinimumSize(new java.awt.Dimension(26, 26));
        buttonFontColourLabel.setOpaque(true);
        buttonFontColourLabel.setPreferredSize(new java.awt.Dimension(26, 26));

        windowFontColourRevertButton.setText("Revert to default");
        windowFontColourRevertButton.setMaximumSize(new java.awt.Dimension(70, 26));
        windowFontColourRevertButton.setMinimumSize(new java.awt.Dimension(70, 26));
        windowFontColourRevertButton.setPreferredSize(new java.awt.Dimension(70, 26));
        windowFontColourRevertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                windowFontColourRevertButtonActionPerformed(evt);
            }
        });

        buttonFontColourRevertButton.setText("Revert to default");
        buttonFontColourRevertButton.setMaximumSize(new java.awt.Dimension(70, 26));
        buttonFontColourRevertButton.setMinimumSize(new java.awt.Dimension(70, 26));
        buttonFontColourRevertButton.setPreferredSize(new java.awt.Dimension(70, 26));
        buttonFontColourRevertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFontColourRevertButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel37Layout = new javax.swing.GroupLayout(jPanel37);
        jPanel37.setLayout(jPanel37Layout);
        jPanel37Layout.setHorizontalGroup(
            jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel37Layout.createSequentialGroup()
                .addGroup(jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel37Layout.createSequentialGroup()
                        .addGroup(jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel37Layout.createSequentialGroup()
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(68, 68, 68))
                            .addGroup(jPanel37Layout.createSequentialGroup()
                                .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(buttonFontColourLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(windowFontColourLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel37Layout.createSequentialGroup()
                                .addComponent(buttonFontColourChooserButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonFontColourRevertButton, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel37Layout.createSequentialGroup()
                                .addComponent(labelFontColourChooserButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(windowFontColourRevertButton, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel37Layout.setVerticalGroup(
            jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel37Layout.createSequentialGroup()
                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel37Layout.createSequentialGroup()
                        .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel37Layout.createSequentialGroup()
                        .addGroup(jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(windowFontColourLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(labelFontColourChooserButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(windowFontColourRevertButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(buttonFontColourChooserButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(buttonFontColourRevertButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(buttonFontColourLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel17)
                    .addComponent(jPanel37, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(163, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(263, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void windowBackgroundColourChooserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_windowBackgroundColourChooserButtonActionPerformed
        windowBackgroundColourChooserButton.setEnabled(false);
        Color color = JColorChooser.showDialog(
                GUI.getInstance(),
                "Choose Background Color",
                null);
        if (color != null) {
            GUIConfig.WINDOW_BG_COLOUR = color;
            windowBackgroundColourLabel.setBackground(color);
            GUIHelperMethods.setOppositeColourDashedBorder(windowBackgroundColourLabel);
            UIManager.put("OptionPane.background", new ColorUIResource(GUIConfig.WINDOW_BG_COLOUR));
            UIManager.put("Panel.background", new ColorUIResource(GUIConfig.WINDOW_BG_COLOUR));
        }
        GUIHelperMethods.setAllGUIColours();
        windowBackgroundColourChooserButton.setEnabled(true);
    }//GEN-LAST:event_windowBackgroundColourChooserButtonActionPerformed

    private void buttonBackgroundColourChooserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBackgroundColourChooserButtonActionPerformed
        buttonBackgroundColourChooserButton.setEnabled(false);
        Color color = JColorChooser.showDialog(
                GUI.getInstance(),
                "Choose Background Color",
                null);
        if (color != null) {
            GUIConfig.JBUTTON_BG_COLOUR = color;
            buttonBackgroundColourLabel.setBackground(color);
            GUIHelperMethods.setOppositeColourDashedBorder(buttonBackgroundColourLabel);
        }
        GUIHelperMethods.setAllGUIColours();
        buttonBackgroundColourChooserButton.setEnabled(true);
    }//GEN-LAST:event_buttonBackgroundColourChooserButtonActionPerformed

    private void buttonFontColourChooserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFontColourChooserButtonActionPerformed
        buttonFontColourChooserButton.setEnabled(false);
        Color color = JColorChooser.showDialog(
                GUI.getInstance(),
                "Choose Background Color",
                null);
        if (color != null) {
            GUIConfig.JBUTTON_FONT_COLOUR = color;
            buttonFontColourLabel.setBackground(color);
            GUIHelperMethods.setOppositeColourDashedBorder(buttonFontColourLabel);
        }
        GUIHelperMethods.setAllGUIColours();
        buttonFontColourChooserButton.setEnabled(true);
    }//GEN-LAST:event_buttonFontColourChooserButtonActionPerformed

    private void labelFontColourChooserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labelFontColourChooserButtonActionPerformed
        labelFontColourChooserButton.setEnabled(false);
        Color color = JColorChooser.showDialog(
                GUI.getInstance(),
                "Choose Background Color",
                null);
        if (color != null) {
            GUIConfig.WINDOW_FONT_COLOUR = color;
            windowFontColourLabel.setBackground(color);
            GUIHelperMethods.setOppositeColourDashedBorder(windowFontColourLabel);
        }
        GUIHelperMethods.setAllGUIColours();
        labelFontColourChooserButton.setEnabled(true);
    }//GEN-LAST:event_labelFontColourChooserButtonActionPerformed

    private void windowFontColourRevertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_windowFontColourRevertButtonActionPerformed
        windowFontColourRevertButton.setEnabled(false);
        Color defaultColor = new Color(200, 200, 200);
        GUIConfig.WINDOW_FONT_COLOUR = defaultColor;
        windowFontColourLabel.setBackground(defaultColor);
        GUIHelperMethods.setOppositeColourDashedBorder(windowFontColourLabel);
        String colourString = String.valueOf(defaultColor.getRed()).concat(",").concat(String.valueOf(defaultColor.getGreen()))
                .concat(",").concat(String.valueOf(defaultColor.getBlue()));
        ConfigDB.updateConfigItem(GUIConfig.P_WINDOW_FONT_COLOUR, colourString);
        GUIHelperMethods.setAllGUIColours();
        windowFontColourRevertButton.setEnabled(true);
    }//GEN-LAST:event_windowFontColourRevertButtonActionPerformed

    private void buttonFontColourRevertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFontColourRevertButtonActionPerformed
        buttonFontColourRevertButton.setEnabled(false);
        Color defaultColor = new Color(200, 200, 200);
        GUIConfig.JBUTTON_FONT_COLOUR = defaultColor;
        buttonFontColourLabel.setBackground(defaultColor);
        GUIHelperMethods.setOppositeColourDashedBorder(buttonFontColourLabel);
        GUIHelperMethods.setAllGUIColours();
        buttonFontColourRevertButton.setEnabled(true);
    }//GEN-LAST:event_buttonFontColourRevertButtonActionPerformed

    private void buttonBackgroundColourRevertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBackgroundColourRevertButtonActionPerformed
        buttonBackgroundColourRevertButton.setEnabled(false);
        Color defaultColor = new Color(0, 102, 102);
        GUIConfig.JBUTTON_BG_COLOUR = defaultColor;
        buttonBackgroundColourLabel.setBackground(defaultColor);
        GUIHelperMethods.setOppositeColourDashedBorder(buttonBackgroundColourLabel);
        GUIHelperMethods.setAllGUIColours();
        buttonBackgroundColourRevertButton.setEnabled(true);
    }//GEN-LAST:event_buttonBackgroundColourRevertButtonActionPerformed

    private void windowBackgroundColourRevertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_windowBackgroundColourRevertButtonActionPerformed
        windowBackgroundColourRevertButton.setEnabled(false);
        Color defaultColor = new Color(55, 60, 74);
        GUIConfig.WINDOW_BG_COLOUR = defaultColor;
        windowBackgroundColourLabel.setBackground(defaultColor);
        GUIHelperMethods.setOppositeColourDashedBorder(windowBackgroundColourLabel);
        GUIHelperMethods.setAllGUIColours();
        windowBackgroundColourRevertButton.setEnabled(true);
    }//GEN-LAST:event_windowBackgroundColourRevertButtonActionPerformed

    @Override
    public void addNameMappings() {

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBackgroundColourChooserButton;
    private com.antsstyle.artretweeter.gui.configuration.ColourPreviewLabel buttonBackgroundColourLabel;
    private javax.swing.JButton buttonBackgroundColourRevertButton;
    private javax.swing.JButton buttonFontColourChooserButton;
    private com.antsstyle.artretweeter.gui.configuration.ColourPreviewLabel buttonFontColourLabel;
    private javax.swing.JButton buttonFontColourRevertButton;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JButton labelFontColourChooserButton;
    private javax.swing.JButton windowBackgroundColourChooserButton;
    private com.antsstyle.artretweeter.gui.configuration.ColourPreviewLabel windowBackgroundColourLabel;
    private javax.swing.JButton windowBackgroundColourRevertButton;
    private com.antsstyle.artretweeter.gui.configuration.ColourPreviewLabel windowFontColourLabel;
    private javax.swing.JButton windowFontColourRevertButton;
    // End of variables declaration//GEN-END:variables
}
