/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.antsstyle.artretweeter.gui.configuration;

import com.antsstyle.artretweeter.configuration.Config;
import com.antsstyle.artretweeter.configuration.GUIConfig;
import com.antsstyle.artretweeter.gui.GUIHelperMethods;
import java.util.ArrayList;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

/**
 *
 * @author antss
 */
public class ConfigurationPrimaryPanel extends javax.swing.JPanel {

    private static final Logger LOGGER = LogManager.getLogger(ConfigurationPrimaryPanel.class);

    private final ArrayList<ConfigurationSubPanel> subPanels = new ArrayList<>();

    /**
     * Creates new form ConfigurationPanel
     */
    public ConfigurationPrimaryPanel() {
        initComponents();
        // Add subpanels
        subPanels.add(appearanceConfigurationPanel);
        subPanels.add(miscConfigurationPanel);
        subPanels.add(twitterConfigurationPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        configChangesStatusLabel = new javax.swing.JLabel();
        saveConfigChangesButton = new javax.swing.JButton();
        configTabbedPane = new javax.swing.JTabbedPane();
        twitterConfigurationPanel = new com.antsstyle.artretweeter.gui.configuration.TwitterConfigurationPanel();
        miscConfigurationPanel = new com.antsstyle.artretweeter.gui.configuration.MiscConfigurationPanel();
        appearanceConfigurationPanel = new com.antsstyle.artretweeter.gui.configuration.AppearanceConfigurationPanel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Configuration");
        jLabel1.setMaximumSize(new java.awt.Dimension(124, 44));
        jLabel1.setMinimumSize(new java.awt.Dimension(124, 44));
        jLabel1.setPreferredSize(new java.awt.Dimension(124, 44));

        configChangesStatusLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        configChangesStatusLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        configChangesStatusLabel.setMaximumSize(new java.awt.Dimension(616, 44));
        configChangesStatusLabel.setMinimumSize(new java.awt.Dimension(616, 44));
        configChangesStatusLabel.setPreferredSize(new java.awt.Dimension(616, 44));

        saveConfigChangesButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        saveConfigChangesButton.setText("Save Changes");
        saveConfigChangesButton.setMaximumSize(new java.awt.Dimension(226, 44));
        saveConfigChangesButton.setMinimumSize(new java.awt.Dimension(226, 44));
        saveConfigChangesButton.setPreferredSize(new java.awt.Dimension(226, 44));
        saveConfigChangesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveConfigChangesButtonActionPerformed(evt);
            }
        });

        configTabbedPane.setMaximumSize(new java.awt.Dimension(810, 464));
        configTabbedPane.setMinimumSize(new java.awt.Dimension(810, 464));
        configTabbedPane.setPreferredSize(new java.awt.Dimension(810, 464));
        configTabbedPane.addTab("Twitter", twitterConfigurationPanel);
        configTabbedPane.addTab("Misc", miscConfigurationPanel);
        configTabbedPane.addTab("Appearance", appearanceConfigurationPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(configTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(configChangesStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saveConfigChangesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(configChangesStatusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(saveConfigChangesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(configTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void saveConfigChangesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveConfigChangesButtonActionPerformed
        try {
            commitChanges();
            GUIHelperMethods.setTemporaryLabelText(configChangesStatusLabel, GUIConfig.WINDOW_FONT_COLOUR,
                    "Changes saved successfully.", 5000);
        } catch (Exception e) {
            LOGGER.error("Failed to save configuration changes!", e);
            GUIHelperMethods.setTemporaryLabelText(configChangesStatusLabel, GUIConfig.WINDOW_FONT_COLOUR,
                    "Error saving configuration changes - check log output.", 5000);
        }
    }//GEN-LAST:event_saveConfigChangesButtonActionPerformed

    public void initialise() {
        for (ConfigurationSubPanel panel : subPanels) {
            panel.initialisePanel();
        }
    }

    private void commitChanges() {
        for (ConfigurationSubPanel panel : subPanels) {
            panel.commitChanges();
        }
        Config.refreshConfigurations();
        Config.initialise();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.antsstyle.artretweeter.gui.configuration.AppearanceConfigurationPanel appearanceConfigurationPanel;
    private javax.swing.JLabel configChangesStatusLabel;
    private javax.swing.JTabbedPane configTabbedPane;
    private javax.swing.JLabel jLabel1;
    private com.antsstyle.artretweeter.gui.configuration.MiscConfigurationPanel miscConfigurationPanel;
    private javax.swing.JButton saveConfigChangesButton;
    private com.antsstyle.artretweeter.gui.configuration.TwitterConfigurationPanel twitterConfigurationPanel;
    // End of variables declaration//GEN-END:variables
}
