/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.antsstyle.artretweeter.gui.configuration;

import com.antsstyle.artretweeter.configuration.Config;
import com.antsstyle.artretweeter.configuration.MiscConfig;
import java.io.File;
import java.nio.file.Paths;
import javax.swing.JFileChooser;
import javax.swing.UIManager;

/**
 *
 * @author antss
 */
public class MiscConfigurationPanel extends ConfigurationSubPanel {

    /**
     * Creates new form MiscConfigurationPanel
     */
    public MiscConfigurationPanel() {
        super(Config.miscConfig);
        initComponents();
        chooseServerRequestDirectoryLabel.setText(
                "Current path: ".concat(MiscConfig.DEBUG_LAST_SERVER_REQUEST_OUTPUT_FILE_PATH.toString()));
        chooseTwitterAPIRequestDirectoryLabel.setText(
                "Current path: ".concat(MiscConfig.DEBUG_LAST_TWITTERAPI_REQUEST_OUTPUT_FILE_PATH.toString()));
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        enableDebugModeCheckBox = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        chooseLastServerRequestFilePathButton = new javax.swing.JButton();
        chooseServerRequestDirectoryLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        chooseLastTwitterAPIRequestFilePathButton = new javax.swing.JButton();
        chooseTwitterAPIRequestDirectoryLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        enableDebugModeCheckBox.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        enableDebugModeCheckBox.setText("Enable Debug Mode");
        enableDebugModeCheckBox.setToolTipText("");
        enableDebugModeCheckBox.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        enableDebugModeCheckBox.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Debug Mode");

        chooseLastServerRequestFilePathButton.setIcon(UIManager.getIcon("FileView.directoryIcon"));
        chooseLastServerRequestFilePathButton.setMaximumSize(new java.awt.Dimension(23, 23));
        chooseLastServerRequestFilePathButton.setMinimumSize(new java.awt.Dimension(23, 23));
        chooseLastServerRequestFilePathButton.setPreferredSize(new java.awt.Dimension(23, 23));
        chooseLastServerRequestFilePathButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseLastServerRequestFilePathButtonActionPerformed(evt);
            }
        });

        chooseServerRequestDirectoryLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        chooseServerRequestDirectoryLabel.setText("Current path: none");
        chooseServerRequestDirectoryLabel.setMaximumSize(new java.awt.Dimension(627, 31));
        chooseServerRequestDirectoryLabel.setMinimumSize(new java.awt.Dimension(627, 31));
        chooseServerRequestDirectoryLabel.setPreferredSize(new java.awt.Dimension(627, 31));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Set path for last server request file");
        jLabel2.setMaximumSize(new java.awt.Dimension(266, 32));
        jLabel2.setMinimumSize(new java.awt.Dimension(266, 32));
        jLabel2.setPreferredSize(new java.awt.Dimension(266, 32));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Set path for last Twitter API request file");
        jLabel3.setMaximumSize(new java.awt.Dimension(266, 32));
        jLabel3.setMinimumSize(new java.awt.Dimension(266, 32));
        jLabel3.setPreferredSize(new java.awt.Dimension(266, 32));

        chooseLastTwitterAPIRequestFilePathButton.setIcon(UIManager.getIcon("FileView.directoryIcon"));
        chooseLastTwitterAPIRequestFilePathButton.setMaximumSize(new java.awt.Dimension(23, 23));
        chooseLastTwitterAPIRequestFilePathButton.setMinimumSize(new java.awt.Dimension(23, 23));
        chooseLastTwitterAPIRequestFilePathButton.setPreferredSize(new java.awt.Dimension(23, 23));
        chooseLastTwitterAPIRequestFilePathButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseLastTwitterAPIRequestFilePathButtonActionPerformed(evt);
            }
        });

        chooseTwitterAPIRequestDirectoryLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        chooseTwitterAPIRequestDirectoryLabel.setText("Current path: none");
        chooseTwitterAPIRequestDirectoryLabel.setMaximumSize(new java.awt.Dimension(627, 31));
        chooseTwitterAPIRequestDirectoryLabel.setMinimumSize(new java.awt.Dimension(627, 31));
        chooseTwitterAPIRequestDirectoryLabel.setPreferredSize(new java.awt.Dimension(627, 31));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("<html>When debug mode is enabled, the last requests made to the ArtRetweeter server and the Twitter API are logged to file.<html>");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(chooseLastServerRequestFilePathButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(chooseLastTwitterAPIRequestFilePathButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(329, 329, 329))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(enableDebugModeCheckBox))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(chooseServerRequestDirectoryLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chooseTwitterAPIRequestDirectoryLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enableDebugModeCheckBox)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(chooseLastServerRequestFilePathButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chooseServerRequestDirectoryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(chooseLastTwitterAPIRequestFilePathButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chooseTwitterAPIRequestDirectoryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(157, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void chooseLastServerRequestFilePathButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseLastServerRequestFilePathButtonActionPerformed
        JFileChooser fc = new JFileChooser();
        fc.setSelectedFile(new File(System.getProperty("user.dir")));
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int result = fc.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            MiscConfig.DEBUG_LAST_SERVER_REQUEST_OUTPUT_FILE_PATH = fc.getSelectedFile().toPath().resolve("lastserverrequest.txt");
            chooseServerRequestDirectoryLabel.setText(
                    "Current path: ".concat(MiscConfig.DEBUG_LAST_SERVER_REQUEST_OUTPUT_FILE_PATH.toString()));
        }
    }//GEN-LAST:event_chooseLastServerRequestFilePathButtonActionPerformed

    private void chooseLastTwitterAPIRequestFilePathButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseLastTwitterAPIRequestFilePathButtonActionPerformed
        JFileChooser fc = new JFileChooser();
        fc.setSelectedFile(new File(System.getProperty("user.dir")));
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int result = fc.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            MiscConfig.DEBUG_LAST_TWITTERAPI_REQUEST_OUTPUT_FILE_PATH = fc.getSelectedFile().toPath().resolve("lasttwitterapirequest.txt");
            chooseTwitterAPIRequestDirectoryLabel.setText(
                    "Current path: ".concat(MiscConfig.DEBUG_LAST_TWITTERAPI_REQUEST_OUTPUT_FILE_PATH.toString()));
        }
    }//GEN-LAST:event_chooseLastTwitterAPIRequestFilePathButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton chooseLastServerRequestFilePathButton;
    private javax.swing.JButton chooseLastTwitterAPIRequestFilePathButton;
    private javax.swing.JLabel chooseServerRequestDirectoryLabel;
    private javax.swing.JLabel chooseTwitterAPIRequestDirectoryLabel;
    private javax.swing.JCheckBox enableDebugModeCheckBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    @Override
    protected void addNameMappings() {
        nameMappings.put(enableDebugModeCheckBox, MiscConfig.P_DEBUG_MODE);
    }
}
