/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.antsstyle.artretweeter.gui.configuration;

import com.antsstyle.artretweeter.configuration.Config;
import com.antsstyle.artretweeter.configuration.MiscConfig;
import java.io.File;
import java.nio.file.Paths;
import javax.swing.JFileChooser;
import javax.swing.UIManager;

/**
 *
 * @author antss
 */
public class MiscConfigurationPanel extends ConfigurationSubPanel {

    /**
     * Creates new form MiscConfigurationPanel
     */
    public MiscConfigurationPanel() {
        super(Config.miscConfig);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        enableDebugModeCheckBox = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        chooseLastServerRequestFilePathButton = new javax.swing.JButton();
        chooseDirectoryLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        chooseLastTwitterAPIRequestFilePathButton = new javax.swing.JButton();
        chooseDirectoryLabel1 = new javax.swing.JLabel();

        enableDebugModeCheckBox.setText("Enable Debug Mode");
        enableDebugModeCheckBox.setToolTipText("");
        enableDebugModeCheckBox.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        enableDebugModeCheckBox.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel1.setText("Debug Mode");

        chooseLastServerRequestFilePathButton.setIcon(UIManager.getIcon("FileView.directoryIcon"));
        chooseLastServerRequestFilePathButton.setMaximumSize(new java.awt.Dimension(23, 23));
        chooseLastServerRequestFilePathButton.setMinimumSize(new java.awt.Dimension(23, 23));
        chooseLastServerRequestFilePathButton.setPreferredSize(new java.awt.Dimension(23, 23));
        chooseLastServerRequestFilePathButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseLastServerRequestFilePathButtonActionPerformed(evt);
            }
        });

        chooseDirectoryLabel.setText("Current path: none");
        chooseDirectoryLabel.setPreferredSize(new java.awt.Dimension(400, 23));

        jLabel2.setText("Set path for last server request file:");

        jLabel3.setText("Set path for last Twitter API request file:");

        chooseLastTwitterAPIRequestFilePathButton.setIcon(UIManager.getIcon("FileView.directoryIcon"));
        chooseLastTwitterAPIRequestFilePathButton.setMaximumSize(new java.awt.Dimension(23, 23));
        chooseLastTwitterAPIRequestFilePathButton.setMinimumSize(new java.awt.Dimension(23, 23));
        chooseLastTwitterAPIRequestFilePathButton.setPreferredSize(new java.awt.Dimension(23, 23));
        chooseLastTwitterAPIRequestFilePathButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseLastTwitterAPIRequestFilePathButtonActionPerformed(evt);
            }
        });

        chooseDirectoryLabel1.setText("Current path: none");
        chooseDirectoryLabel1.setPreferredSize(new java.awt.Dimension(400, 23));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(enableDebugModeCheckBox)
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(chooseLastTwitterAPIRequestFilePathButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chooseDirectoryLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(chooseLastServerRequestFilePathButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chooseDirectoryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(15, 15, 15)
                .addComponent(enableDebugModeCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(chooseDirectoryLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chooseLastServerRequestFilePathButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(chooseDirectoryLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chooseLastTwitterAPIRequestFilePathButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(222, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void chooseLastServerRequestFilePathButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseLastServerRequestFilePathButtonActionPerformed
        JFileChooser fc = new JFileChooser();
        fc.setSelectedFile(new File(System.getProperty("user.dir")));
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int result = fc.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            MiscConfig.DEBUG_LAST_SERVER_REQUEST_OUTPUT_FILE_PATH = fc.getSelectedFile().toPath();
            chooseDirectoryLabel.setText("Selected directory: ".concat(MiscConfig.DEBUG_LAST_SERVER_REQUEST_OUTPUT_FILE_PATH.toString()));
        }
    }//GEN-LAST:event_chooseLastServerRequestFilePathButtonActionPerformed

    private void chooseLastTwitterAPIRequestFilePathButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseLastTwitterAPIRequestFilePathButtonActionPerformed
        JFileChooser fc = new JFileChooser();
        fc.setSelectedFile(new File(System.getProperty("user.dir")));
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int result = fc.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            MiscConfig.DEBUG_LAST_TWITTERAPI_REQUEST_OUTPUT_FILE_PATH = fc.getSelectedFile().toPath();
            chooseDirectoryLabel.setText("Selected directory: ".concat(MiscConfig.DEBUG_LAST_TWITTERAPI_REQUEST_OUTPUT_FILE_PATH.toString()));
        }
    }//GEN-LAST:event_chooseLastTwitterAPIRequestFilePathButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel chooseDirectoryLabel;
    private javax.swing.JLabel chooseDirectoryLabel1;
    private javax.swing.JButton chooseLastServerRequestFilePathButton;
    private javax.swing.JButton chooseLastTwitterAPIRequestFilePathButton;
    private javax.swing.JCheckBox enableDebugModeCheckBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    @Override
    protected void addNameMappings() {
        nameMappings.put(enableDebugModeCheckBox, MiscConfig.P_DEBUG_MODE);
    }
}
