/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.antsstyle.artretweeter.gui.configuration;

import com.antsstyle.artretweeter.configuration.Config;
import com.antsstyle.artretweeter.configuration.TwitterConfig;

/**
 *
 * @author antss
 */
public class TwitterConfigurationPanel extends ConfigurationSubPanel {

    /**
     * Creates new form TwitterConfigurationPanel
     */
    public TwitterConfigurationPanel() {
        super(Config.twitterConfig);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        downloadTweetsAutomaticallyCheckBox = new javax.swing.JCheckBox();
        jLabel55 = new javax.swing.JLabel();
        checkForNewTweetsFrequencyField = new javax.swing.JTextField();
        checkForNewTweetsFrequencyCheckBox = new javax.swing.JComboBox<>();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Automatic Tweet Retrieval");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("<html>ArtRetweeter can automatically check for new tweets from your accounts and download them at set intervals. (The most frequent setting allowed is every 30 minutes.)</html>");

        downloadTweetsAutomaticallyCheckBox.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        downloadTweetsAutomaticallyCheckBox.setText("Download tweets automatically");
        downloadTweetsAutomaticallyCheckBox.setToolTipText("");
        downloadTweetsAutomaticallyCheckBox.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        downloadTweetsAutomaticallyCheckBox.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel55.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel55.setText("Check for new tweets every:");
        jLabel55.setToolTipText("");

        checkForNewTweetsFrequencyField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        checkForNewTweetsFrequencyField.setMaximumSize(new java.awt.Dimension(99, 24));
        checkForNewTweetsFrequencyField.setMinimumSize(new java.awt.Dimension(99, 24));
        checkForNewTweetsFrequencyField.setPreferredSize(new java.awt.Dimension(99, 24));

        checkForNewTweetsFrequencyCheckBox.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        checkForNewTweetsFrequencyCheckBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Minutes", "Hours", "Days" }));
        checkForNewTweetsFrequencyCheckBox.setMaximumSize(new java.awt.Dimension(97, 24));
        checkForNewTweetsFrequencyCheckBox.setMinimumSize(new java.awt.Dimension(97, 24));
        checkForNewTweetsFrequencyCheckBox.setPreferredSize(new java.awt.Dimension(97, 24));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel55)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkForNewTweetsFrequencyField, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkForNewTweetsFrequencyCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(downloadTweetsAutomaticallyCheckBox))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(downloadTweetsAutomaticallyCheckBox)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(checkForNewTweetsFrequencyField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(checkForNewTweetsFrequencyCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel55, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(241, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> checkForNewTweetsFrequencyCheckBox;
    private javax.swing.JTextField checkForNewTweetsFrequencyField;
    private javax.swing.JCheckBox downloadTweetsAutomaticallyCheckBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    @Override
    protected void addNameMappings() {
        nameMappings.put(downloadTweetsAutomaticallyCheckBox, TwitterConfig.P_CHECK_NEW_TWEETS_ENABLED);
        nameMappings.put(checkForNewTweetsFrequencyField, TwitterConfig.P_CHECK_NEW_TWEETS_FREQUENCY);
        nameMappings.put(checkForNewTweetsFrequencyCheckBox, TwitterConfig.P_CHECK_NEW_TWEETS_FREQUENCY_TIME_UNITS);
    }
}
