/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.antsstyle.artretweeter.gui.configuration;

import com.antsstyle.artretweeter.configuration.Config;
import com.antsstyle.artretweeter.configuration.TwitterConfig;

/**
 *
 * @author antss
 */
public class TwitterConfigurationPanel extends ConfigurationSubPanel {

    /**
     * Creates new form TwitterConfigurationPanel
     */
    public TwitterConfigurationPanel() {
        super(Config.twitterConfig);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        downloadTweetsAutomaticallyCheckBox = new javax.swing.JCheckBox();
        jLabel55 = new javax.swing.JLabel();
        checkForNewTweetsFrequencyField = new javax.swing.JTextField();
        checkForNewTweetsFrequencyCheckBox = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        downloadCollectionsAutomaticallyCheckBox = new javax.swing.JCheckBox();
        jLabel56 = new javax.swing.JLabel();
        checkForNewCollectionsFrequencyField = new javax.swing.JTextField();
        checkForNewCollectionsFrequencyCheckBox = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        doNotShowTwitterMetricsCheckBox = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Automatic Tweet Retrieval");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("<html>ArtRetweeter can automatically check for new tweets from your accounts and download them at set intervals.</html>");

        downloadTweetsAutomaticallyCheckBox.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        downloadTweetsAutomaticallyCheckBox.setText("Download tweets automatically");
        downloadTweetsAutomaticallyCheckBox.setToolTipText("");
        downloadTweetsAutomaticallyCheckBox.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        downloadTweetsAutomaticallyCheckBox.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel55.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel55.setText("Check for new tweets every:");
        jLabel55.setToolTipText("");

        checkForNewTweetsFrequencyField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        checkForNewTweetsFrequencyField.setMaximumSize(new java.awt.Dimension(99, 24));
        checkForNewTweetsFrequencyField.setMinimumSize(new java.awt.Dimension(99, 24));
        checkForNewTweetsFrequencyField.setPreferredSize(new java.awt.Dimension(99, 24));

        checkForNewTweetsFrequencyCheckBox.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        checkForNewTweetsFrequencyCheckBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Minutes", "Hours", "Days" }));
        checkForNewTweetsFrequencyCheckBox.setMaximumSize(new java.awt.Dimension(97, 24));
        checkForNewTweetsFrequencyCheckBox.setMinimumSize(new java.awt.Dimension(97, 24));
        checkForNewTweetsFrequencyCheckBox.setPreferredSize(new java.awt.Dimension(97, 24));

        jLabel8.setText("Maximum frequency: every 30 minutes");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel55)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkForNewTweetsFrequencyField, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkForNewTweetsFrequencyCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(downloadTweetsAutomaticallyCheckBox))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(downloadTweetsAutomaticallyCheckBox)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(checkForNewTweetsFrequencyField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(checkForNewTweetsFrequencyCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel55, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Automatic Collections Retrieval");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("<html>ArtRetweeter can automatically check for new collections, or changes to your existing ones, at set intervals.</html>");

        downloadCollectionsAutomaticallyCheckBox.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        downloadCollectionsAutomaticallyCheckBox.setText("Download and update collections automatically");
        downloadCollectionsAutomaticallyCheckBox.setToolTipText("");
        downloadCollectionsAutomaticallyCheckBox.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        downloadCollectionsAutomaticallyCheckBox.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel56.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel56.setText("Check for new tweets every:");
        jLabel56.setToolTipText("");

        checkForNewCollectionsFrequencyField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        checkForNewCollectionsFrequencyField.setMaximumSize(new java.awt.Dimension(99, 24));
        checkForNewCollectionsFrequencyField.setMinimumSize(new java.awt.Dimension(99, 24));
        checkForNewCollectionsFrequencyField.setPreferredSize(new java.awt.Dimension(99, 24));

        checkForNewCollectionsFrequencyCheckBox.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        checkForNewCollectionsFrequencyCheckBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hours", "Days" }));
        checkForNewCollectionsFrequencyCheckBox.setMaximumSize(new java.awt.Dimension(97, 24));
        checkForNewCollectionsFrequencyCheckBox.setMinimumSize(new java.awt.Dimension(97, 24));
        checkForNewCollectionsFrequencyCheckBox.setPreferredSize(new java.awt.Dimension(97, 24));

        jLabel7.setText("Maximum frequency: every 6 hours");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel56)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkForNewCollectionsFrequencyField, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkForNewCollectionsFrequencyCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(downloadCollectionsAutomaticallyCheckBox))
                .addContainerGap(158, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(12, 12, 12)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(downloadCollectionsAutomaticallyCheckBox)
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(checkForNewCollectionsFrequencyField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(checkForNewCollectionsFrequencyCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel56, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Twitter Metrics: Retweets & Likes");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("<html>By default, showing retweets & likes in the Tweet Management tables is disabled, as many artists prefer not to see them. If you want to see them, you can disable this option.</html>");

        doNotShowTwitterMetricsCheckBox.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        doNotShowTwitterMetricsCheckBox.setText("Do not show any Twitter metrics");
        doNotShowTwitterMetricsCheckBox.setToolTipText("");
        doNotShowTwitterMetricsCheckBox.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        doNotShowTwitterMetricsCheckBox.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doNotShowTwitterMetricsCheckBox))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(doNotShowTwitterMetricsCheckBox)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("<html>The settings in this panel apply only to the ArtRetweeter client on your computer.<br/><br/>They are not needed for the automation settings to function, as those are handled by the ArtRetweeter server.</html>");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> checkForNewCollectionsFrequencyCheckBox;
    private javax.swing.JTextField checkForNewCollectionsFrequencyField;
    private javax.swing.JComboBox<String> checkForNewTweetsFrequencyCheckBox;
    private javax.swing.JTextField checkForNewTweetsFrequencyField;
    private javax.swing.JCheckBox doNotShowTwitterMetricsCheckBox;
    private javax.swing.JCheckBox downloadCollectionsAutomaticallyCheckBox;
    private javax.swing.JCheckBox downloadTweetsAutomaticallyCheckBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables

    @Override
    protected void addNameMappings() {
        nameMappings.put(downloadTweetsAutomaticallyCheckBox, TwitterConfig.P_CHECK_NEW_TWEETS_ENABLED);
        nameMappings.put(checkForNewTweetsFrequencyField, TwitterConfig.P_CHECK_NEW_TWEETS_FREQUENCY);
        nameMappings.put(checkForNewTweetsFrequencyCheckBox, TwitterConfig.P_CHECK_NEW_TWEETS_FREQUENCY_TIME_UNITS);
        nameMappings.put(downloadCollectionsAutomaticallyCheckBox, TwitterConfig.P_CHECK_NEW_COLLECTIONS_ENABLED);
        nameMappings.put(checkForNewCollectionsFrequencyField, TwitterConfig.P_CHECK_NEW_COLLECTIONS_FREQUENCY);
        nameMappings.put(checkForNewCollectionsFrequencyCheckBox, TwitterConfig.P_CHECK_NEW_COLLECTIONS_FREQUENCY_TIME_UNITS);
        nameMappings.put(doNotShowTwitterMetricsCheckBox, TwitterConfig.P_DO_NOT_SHOW_METRICS_ANYWHERE);
    }
}
